---
driver:
  name: vagrant

  provisioner:
    name: chef_zero

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[cas_logrotate::default]
    attributes: 
      cas_logrotate:
        entries:
          example:
            logs: '/var/log/example/*.log'
            su: 'root root'
            frequency: 'daily'
            notifempty: true
            size: '1m'
            rotate: '10'
            maxage: '14'
            create: '0644 root root'
            compress: true
            delaycompress: true
            dateext: true
            missingok: true
            copytruncate: true
            prerotate: 'echo "prerotate command"'
            postrotate: 'echo "postrotate command"'
            sharedscripts: true
